apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: alpha
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      port: 2347
      protocol: TCP
      targetPort: 8000