[package]
name = "app3"
version = "0.0.1"
authors = ["Tapani Honkanen <tapani.honkanen@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
