apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-dep
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      volumes:
        - name: image-cache
          emptyDir: {}
      containers:
        - name: todo-service
          image: tapanih/dwk-todo-service:0.4
          env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_URL
          volumeMounts:
          - name: image-cache
            mountPath: /images