apiVersion: v1
kind: Service
metadata:
  name: todo-service-svc
  namespace: beta
spec:
  type: ClusterIP
  selector:
    app: todo-service
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 8000