apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-application-dep
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-application
  template:
    metadata:
      labels:
        app: main-application
    spec:
      volumes:
        - name: shared-timestamp
          emptyDir: {}
      containers:
        - name: app-response
          image: tapanih/dwk-app-response:0.7
          env:
            - name: PINGPONG_URL
              value: http://pingpong-svc:2347/pongs
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-application-config
                  key: message
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/local/bin/files
        - name: timestamper
          image: tapanih/dwk-timestamper:0.1
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/local/bin/files

