apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-application-ingress
  namespace: alpha
spec:
  rules:
  - http:
      paths:
      - path: /main
        backend:
          serviceName: main-application-svc
          servicePort: 2345
      - path: /pingpong
        backend:
          serviceName: pingpong-svc
          servicePort: 2347
      - path: /pongs
        backend:
          serviceName: pingpong-svc
          servicePort: 2347
